# Generated by Django 3.2 on 2025-04-02 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_pedido_pedidodetalle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='fecha_nasimiento',
            new_name='fecha_nacimiento',
        ),
        migrations.AddField(
            model_name='cliente',
            name='direcion',
            field=models.TextField(default=0.0004940711462450593),
            preserve_default=False,
        ),
    ]
